#!/usr/bin/env python3
"""Fail if a generated table in the docs differs from what the generator produces now.

    python tools/check_generated.py          # exit 1 and print a diff hint if stale
    python tools/check_generated.py --fix    # rewrite the table in place

Currently: the settings table in docs/FIELDS.md, generated by tools/gen_fields_table.py from mk2vsc/fields.py.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(ROOT, "docs", "FIELDS.md")
TABLE_RE = re.compile(r"\| ID \| Offset \|.*?(?=\n\n(?!\|))", re.S)


def main():
    table = subprocess.check_output([sys.executable, os.path.join(ROOT, "tools", "gen_fields_table.py")], text=True).strip()
    doc = open(DOC, encoding="utf-8").read()
    m = TABLE_RE.search(doc)
    if not m:
        print("check_generated: no table found in docs/FIELDS.md")
        return 1
    if m.group(0) == table:
        print("check_generated: docs/FIELDS.md table is up to date")
        return 0
    if "--fix" in sys.argv:
        open(DOC, "w", encoding="utf-8").write(doc[: m.start()] + table + doc[m.end():])
        print("check_generated: docs/FIELDS.md table regenerated")
        return 0
    print("check_generated: docs/FIELDS.md table is STALE relative to mk2vsc/fields.py; run: python tools/check_generated.py --fix")
    return 1


if __name__ == "__main__":
    sys.exit(main())
